#cloud-config
hostname: k8s-master
manage_etc_hosts: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg

users:
  - name: devops
    plain_text_passwd: devops
    groups: sudo
    lock_passwd: false
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0Yp6xPoHfV5hM4KFjCvHZ2ytzBeRboU3OEYE0mWU3XRVGDKUmroRy2SjioKLVV5HvibVhghlrmMS/FTGMWu7glY8MtcuaPszI6yIWy5o0/Jtck8dsZxgYIx5q18i8uT7kLQPHWuwIzyIEBv9qlNwhTpy26BElnOq1cP2p+l+9+Ba7VSgL//napl6QKm1g0rF0hrn1h2VLMiBecgg7j6SB+JVvzZIgB9lNAmoj1MmhGDvQQCv3B9mJhfyGPsH+K3IN72RGfE5MXdQzefB9l5jlxY8+DUY8stcJZ/rczlbQjPP+v6Z6mMkp1Jy0NnhqESQg6D2fx+KtQcysDQgYoLfUNVYsSxGW5kqm3Qe9AmvQewUZ5BTt9ZBkFeK1tU7ZBeIBIGMo0WSj0yd6zgfW7JUrxdj5byfV2nW131Y2mxO3DqUCjZK/LvGiah0iYYfSSIRrMx8fDopN/PXlSWrkL+9xqopByS0w7UabjanXtCLSvpNXdeP/IuDh2DbVbN8Ipdc= your_email@example.com

runcmd:
  # Set up hosts file
  - echo "192.168.1.10 k8s-master" >> /etc/hosts
  - echo "192.168.1.11 k8s-worker" >> /etc/hosts

  # Install Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  # Install Kubernetes
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

  # update and install packages
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - apt-get install -y kubelet kubeadm kubectl
  - apt-mark hold kubelet kubeadm kubectl

  # Configure containerd
  - containerd config default | sudo tee /etc/containerd/config.toml >/dev/null
  - sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
  - sudo systemctl restart containerd

  # create cluster
  - kubeadm init --pod-network-cidr=192.168.0.0/16
  - mkdir -p /root/.kube
  - cp /etc/kubernetes/admin.conf /root/.kube/config
  - mkdir -p /home/devops/.kube
  - cp /etc/kubernetes/admin.conf /home/devops/.kube/config
  - chown devops:devops /home/devops/.kube/config

  # Install Calico CNI
  - kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml

  # create join command for worker
  - kubeadm token create --print-join-command > /join-command.sh

final_message: "master node setup complete! To join worker nodes, run the following command: sudo $(cat /join-command.sh)"