#cloud-config
users:
  - name: ubuntu
    plain_text_passwd: ubuntu
    lock_passwd: false
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0Yp6xPoHfV5hM4KFjCvHZ2ytzBeRboU3OEYE0mWU3XRVGDKUmroRy2SjioKLVV5HvibVhghlrmMS/FTGMWu7glY8MtcuaPszI6yIWy5o0/Jtck8dsZxgYIx5q18i8uT7kLQPHWuwIzyIEBv9qlNwhTpy26BElnOq1cP2p+l+9+Ba7VSgL//napl6QKm1g0rF0hrn1h2VLMiBecgg7j6SB+JVvzZIgB9lNAmoj1MmhGDvQQCv3B9mJhfyGPsH+K3IN72RGfE5MXdQzefB9l5jlxY8+DUY8stcJZ/rczlbQjPP+v6Z6mMkp1Jy0NnhqESQg6D2fx+KtQcysDQgYoLfUNVYsSxGW5kqm3Qe9AmvQewUZ5BTt9ZBkFeK1tU7ZBeIBIGMo0WSj0yd6zgfW7JUrxdj5byfV2nW131Y2mxO3DqUCjZK/LvGiah0iYYfSSIRrMx8fDopN/PXlSWrkL+9xqopByS0w7UabjanXtCLSvpNXdeP/IuDh2DbVbN8Ipdc= your_email@example.com

packages:
  - nginx
  - git
  - curl
