#cloud-config
hostname: k8s-master
fqdn: k8s-master.localdomain
manage_etc_hosts: true

package_update: true
package_upgrade: true
packages:
  - curl
  - gnupg2
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - containerd.io
  - kubelet=1.30.0-*
  - kubeadm=1.30.0-*
  - kubectl=1.30.0-*

write_files:
  - path: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter
      
  - path: /etc/sysctl.d/kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

  - path: /etc/containerd/config.toml
    content: |
      version = 2
      [plugins]
        [plugins."io.containerd.grpc.v1.cri"]
          systemd_cgroup = true

users:
  - name: devops
    plain_text_passwd: devops
    groups: sudo
    lock_passwd: false
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0Yp6xPoHfV5hM4KFjCvHZ2ytzBeRboU3OEYE0mWU3XRVGDKUmroRy2SjioKLVV5HvibVhghlrmMS/FTGMWu7glY8MtcuaPszI6yIWy5o0/Jtck8dsZxgYIx5q18i8uT7kLQPHWuwIzyIEBv9qlNwhTpy26BElnOq1cP2p+l+9+Ba7VSgL//napl6QKm1g0rF0hrn1h2VLMiBecgg7j6SB+JVvzZIgB9lNAmoj1MmhGDvQQCv3B9mJhfyGPsH+K3IN72RGfE5MXdQzefB9l5jlxY8+DUY8stcJZ/rczlbQjPP+v6Z6mMkp1Jy0NnhqESQg6D2fx+KtQcysDQgYoLfUNVYsSxGW5kqm3Qe9AmvQewUZ5BTt9ZBkFeK1tU7ZBeIBIGMo0WSj0yd6zgfW7JUrxdj5byfV2nW131Y2mxO3DqUCjZK/LvGiah0iYYfSSIRrMx8fDopN/PXlSWrkL+9xqopByS0w7UabjanXtCLSvpNXdeP/IuDh2DbVbN8Ipdc= your_email@example.com

runcmd:
  # Set up hosts file
  - echo "192.168.1.10 k8s-master" | sudo tee -a /etc/hosts
  - echo "192.168.1.11 k8s-worker" | sudo tee -a /etc/hosts

  # Disable swap
  - swapoff -a
  - sed -i '/swap/d' /etc/fstab

  # Load kernel modules
  - modprobe overlay
  - modprobe br_netfilter
  - sysctl --system

  # Configure containerd
  - mkdir -p /etc/containerd
  - containerd config default > /etc/containerd/config.toml
  - systemctl restart containerd
  - systemctl enable containerd

  # Add Kubernetes repo
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" > /etc/apt/sources.list.d/kubernetes.list
  - apt update
  - apt-mark hold kubelet kubeadm kubectl

  # Initialize Kubernetes cluster
  - kubeadm init --control-plane-endpoint "192.168.1.10:6443" --pod-network-cidr=192.168.0.0/16 > /home/devops/kubeadm-init.log
  - mkdir -p /home/devops/.kube
  - cp /etc/kubernetes/admin.conf /home/devops/.kube/config
  - chown -R devops:devops /home/devops/.kube

  # Install Calico network plugin
  - su - devops -c "kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml"

  # Generate worker join command
  - kubeadm token create --print-join-command > /home/devops/worker-join-command.sh
  - chown devops:devops /home/devops/worker-join-command.sh
  - chmod +x /home/devops/worker-join-command.sh

final_message: "Kubernetes master setup complete. Worker join command: /home/devops/worker-join-command.sh"